name: Publish Doxygen Docs
on:
  push:
    branches: [ main ]
  release:
    types: [ published ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 允许推送
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get install -y doxygen graphviz
      - run: doxygen Doxyfile
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/html
          publish_branch: gh-pages