name: Publish Multi-version Docs
on:
  push:
    branches: [ main, release/* ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen graphviz

      - name: Parse version list
        id: versions
        run: |
          if [ -f ".github/versions.list" ]; then
            VERSIONS=$(grep -v '^#' .github/versions.list | grep -v '^$' | awk '{print $1}' | tr '\n' ' ' | sed 's/ $//')
            echo "versions=${VERSIONS}" >> $GITHUB_OUTPUT
          else
            echo "versions=main" >> $GITHUB_OUTPUT
          fi
          echo "Versions to build: $VERSIONS"

      - name: Build docs
        run: |
          IFS=' ' read -ra VERSION_ARRAY <<< "${{ steps.versions.outputs.versions }}"
          
          for VERSION in "${VERSION_ARRAY[@]}"; do
            echo "Building version: $VERSION"
            
            if [ "$VERSION" = "main" ]; then
              OUT_DIR="latest"
            else
              OUT_DIR="$VERSION"
            fi

            mkdir -p "output/$OUT_DIR"
            cp Doxyfile Doxyfile.tmp
            echo "PROJECT_NUMBER = $VERSION" >> Doxyfile.tmp
            echo "OUTPUT_DIRECTORY = html" >> Doxyfile.tmp
            # 添加版本切换器文件到现有的HTML_EXTRA_FILES和HTML_EXTRA_STYLESHEET
            echo "HTML_EXTRA_FILES += docs/version-switcher.js" >> Doxyfile.tmp
            echo "HTML_EXTRA_STYLESHEET += docs/version-switcher.css" >> Doxyfile.tmp
            doxygen Doxyfile.tmp

            if [ -d "html" ]; then
              mv html/* "output/$OUT_DIR/"
              rm -rf html
            fi
          done

      - name: Generate version manifest
        run: |
          cd output
          # 生成版本列表
          echo '{"versions": [' > versions.json
          ls -d */ | grep -E '^[a-zA-Z0-9]+/' | sed 's/\///g' | sed 's/^/"/' | sed 's/$/"/' | tr '\n' ',' | sed 's/,$//' >> versions.json
          echo ']}' >> versions.json

      - name: Prepare deployment
        run: |
          # 创建根目录重定向
          cat > output/index.html << 'EOF'
          <!DOCTYPE html>
          <html>
          <head>
            <meta charset="utf-8">
            <meta http-equiv="refresh" content="0; url=./latest/html/" />
            <title>Redirecting...</title>
            <script>
              // JavaScript fallback for redirect
              window.location.href = './latest/html/';
            </script>
          </head>
          <body>
            <p>Redirecting to latest version...</p>
            <p>If you are not redirected automatically, <a href="./latest/html/">click here</a>.</p>
          </body>
          </html>
          EOF
          
          # 创建404页面
          cat > output/404.html << 'EOF'
          <!DOCTYPE html>
          <html>
          <head>
            <meta charset="utf-8">
            <meta http-equiv="refresh" content="3; url=./latest/html/" />
            <title>Page Not Found - Redirecting...</title>
            <style>
              body {
                font-family: Arial, sans-serif;
                text-align: center;
                padding: 50px;
                background-color: #f5f5f5;
              }
              .container {
                max-width: 600px;
                margin: 0 auto;
                background: white;
                padding: 30px;
                border-radius: 8px;
                box-shadow: 0 2px 10px rgba(0,0,0,0.1);
              }
              .error-code {
                font-size: 72px;
                color: #e74c3c;
                margin-bottom: 20px;
              }
              .message {
                font-size: 18px;
                color: #333;
                margin-bottom: 20px;
              }
              .link {
                color: #3498db;
                text-decoration: none;
              }
              .link:hover {
                text-decoration: underline;
              }
            </style>
          </head>
          <body>
            <div class="container">
              <div class="error-code">404</div>
              <div class="message">
                <h2>Page Not Found</h2>
                <p>The page you're looking for doesn't exist.</p>
                <p>Redirecting to the latest documentation in 3 seconds...</p>
              </div>
              <p><a href="./latest/html/" class="link">Click here if you're not redirected automatically</a></p>
            </div>
            <script>
              // JavaScript fallback for redirect
              setTimeout(function() {
                window.location.href = './latest/html/';
              }, 3000);
            </script>
          </body>
          </html>
          EOF
          
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
          publish_branch: gh-pages
          keep_files: true