name: Publish Multi-version Docs
on:
  push:
    branches: [ main, release/* ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen graphviz

      - name: Parse version list
        id: versions
        run: |
          # 从 .github/versions.list 提取版本（移除注释和空行）
          if [ -f ".github/versions.list" ]; then
            VERSIONS=$(grep -v '^#' .github/versions.list | grep -v '^$' | tr '\n' ' ' | sed 's/ $//')
            echo "versions=${VERSIONS}" >> $GITHUB_OUTPUT
          else
            echo "versions=main" >> $GITHUB_OUTPUT
          fi
          echo "Versions to build: $VERSIONS"

      - name: Build docs
        run: |
          # 安全分割字符串为数组
          IFS=' ' read -ra VERSION_ARRAY <<< "${{ steps.versions.outputs.versions }}"
          
          for VERSION in "${VERSION_ARRAY[@]}"; do
            echo "Building version: $VERSION"
            
            # 如果是 main 分支，输出到 latest/
            if [ "$VERSION" = "main" ]; then
              OUT_DIR="latest"
            else
              OUT_DIR="$VERSION"
            fi

            # 生成文档
            mkdir -p "output/$OUT_DIR"
            cp Doxyfile Doxyfile.tmp
            echo "PROJECT_NUMBER = $VERSION" >> Doxyfile.tmp
            doxygen Doxyfile.tmp

            # 移动文件到 output/
            if [ -d "html" ]; then
              mv html/* "output/$OUT_DIR/"
            fi
          done

      - name: Generate version manifest
        run: |
          cd output
          echo '{"versions": [' > versions.json
          ls -d */ | sed 's/\///g' | jq -R -s -c 'split("\n")[:-1]' >> versions.json
          echo ']}' >> versions.json

      - name: Prepare deployment
        run: |
          cat > output/index.html << 'EOF'
          <!DOCTYPE html>
          <html>
          <head>
            <meta http-equiv="refresh" content="0; url=./latest/" />
          </head>
          <body>
            Redirecting to latest version...
          </body>
          </html>
          EOF
          
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
          publish_branch: gh-pages
          keep_files: true