name: Publish Multi-version Docs
on:
  push:
    branches: [ main, release/* ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen graphviz

      - name: Parse version list
        id: versions
        run: |
          if [ -f ".github/versions.list" ]; then
            VERSIONS=$(grep -v '^#' .github/versions.list | grep -v '^$' | tr '\n' ' ')
            echo "versions=${VERSIONS}" >> $GITHUB_OUTPUT
          else
            echo "versions=main" >> $GITHUB_OUTPUT
          fi

      - name: Build docs
        run: |
          for VERSION in ${{ steps.versions.outputs.versions }}; do
            if [ "$VERSION" = "main" ]; then
              OUT_DIR="latest"
            else
              OUT_DIR="$VERSION"
            fi
            mkdir -p "output/$OUT_DIR"
            echo "PROJECT_NUMBER = $VERSION" >> Doxyfile
            doxygen Doxyfile
            mv html/* "output/$OUT_DIR/"
          done

      - name: Generate version manifest
        run: |
          cd output
          echo '{"versions": [' > versions.json
          ls -d */ | sed 's/\///g' | jq -R -s -c 'split("\n")[:-1]' >> versions.json
          echo ']}' >> versions.json

      - name: Prepare deployment
        run: |
          cp docs/root-index.html output/index.html
          
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
          publish_branch: gh-pages
          keep_files: true